---
- hosts: "awxnodes"
  user: defaultuser 
  become: yes
  tasks:

  - name: "Create the nececssary folders"
    file:
      path: "{{ item }}"
      state: directory
      owner: root 
      group: admin
      mode: 0775
    loop:
      - /srv/awx/build_image
      - /srv/awx/projects
      - /srv/awx/configs
      - /srv/awx/pass2awx/configs
      - /srv/awx/pass2awx/certs

  - name: "Uncomment/Enable public key authentication via ssh"
    replace:
      path: /etc/ssh/sshd_config
      regexp: '#PubkeyAuthentication yes'
      replace: 'PubkeyAuthentication yes'
      backup: yes
    tags: sshd
    notify:
    - reload sshd

  - name: "Installing necessary packages."
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - gcc
        - git
        - curl 
        - gcc-c++
        - nodejs
        - gettext
        - device-mapper-persistent-data
        - lvm2
        - bzip2
        - python3-pip
        - yum-utils
        - ansible
        - python-pip
        - telnet

  - name: "Installing necessary packages using pip"
    pip:
      name: docker-py,bcrypt==3.1.7,pyOpenSSL

  - name: "Reinstalling a python library"
    pip:
      name: cryptography
      state: forcereinstall

  - name: Copy some files which needed to build images 
    copy:
      src: "{{ item }}"
      dest: /srv/awx/build_image
      owner: root
      group: root
      mode: 0755
    with_items:
      - awx/ansible-2.9.15-1.el8.noarch.rpm
      - awx/Internal_Root_CA_1.pem
      - awx/certinstall.sh

  - name: Ensure if local directory exists for self-signed web server certs.
    file:
      path: /srv/awx/pass2awx/certs/
      state: directory

  - name: Generate a private key.
    openssl_privatekey:
      path: /srv/awx/pass2awx/certs/awxweb.key

  - name: Generate a CSR.
    openssl_csr:
      path: /srv/awx/pass2awx/certs/awxweb.csr
      privatekey_path: /srv/awx/pass2awx/certs/awxweb.key
      common_name: "awxweb"

  - name: Generate a Self Signed web server certificate.
    openssl_certificate:
      path: /srv/awx/pass2awx/certs//awxweb.crt
      privatekey_path: /srv/awx/pass2awx/certs/awxweb.key
      csr_path: /srv/awx/pass2awx/certs/awxweb.csr
      provider: selfsigned

  - name: Copy files and directories from files directory
    copy:
      src: configs
      dest: /srv/awx/pass2awx
      owner: root
      group: root

  - name: "Remove python library" 
    pip:
     name: docker,docker-py
     state: absent

  - name: "Installing necessary packages using pip"
    pip:
     name: docker-py

  - name: Pre-Download awx officialy images for deployment.
    docker_image:
     name: "{{ item.name }}"
     tag: "{{ item.version }}"
    with_items:
      - { name: ansible/awx_web, version: 9.1.1 }
      - { name: ansible/awx_task, version: 9.1.1 }
      - { name: memcached, version: alpine }
    tags: predownloadimages

  - name: "Remove python library"
    pip:
     name: docker-py
     state: absent

  handlers:
    - name: "reload sshd"
      service: 
        name=sshd 
        state=reloaded
