FROM ansible/awx_task:{{ awx_web_tag }} 
USER root
ADD launch_awx.sh /usr/bin/launch_awx.sh
ADD launch_awx_task.sh /usr/bin/launch_awx_task.sh
ADD settings.py /etc/tower/settings.py
RUN yum check-update;yum install -y ansible-2.9.11-1.el8;yum clean all
RUN pip3 install --upgrade setuptools;pip3 install pynetbox
RUN mkdir /root/.ssh;chmod 0700 /root/.ssh
RUN chmod +rx /usr/bin/launch_awx.sh && \
    chmod +rx /usr/bin/launch_awx_task.sh
USER 1000
